audit_header: false
title: East Valley Real Estate Video Blog with Kenny Klaus
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for East Valley
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional East Valley Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Meet Our Team
    url: ' https://www.klausteam.com/agents/'
  - title: Events
    url: /events/
client:
  name: Kenny Klaus
  title:
  license_number:
  about_markdown: >-
    The Kenny Klaus Team is one of the most successful real estate teams in
    America. Since 2010, The Kenny Klaus Team has been consistently ranked in
    the Top 120 teams nationwide by Real Trends and the Wall Street Journal. The
    Kenny Klaus Team sold more Mesa homes than anyone else in 2016.


    The Kenny Klaus Team are the experts in East Valley Real Estate in Arizona.
    With a dedicated team of buyer agents, listing agents, transaction
    coordinators, and with a lender and a title company on-site, The Kenny Klaus
    Team is your one-stop shop for real estate.
  market: East Valley
  brand: Klaus Team Real Estate Solutions
  brokerage: Real Broker
  address: 2919 S Ellsworth Rd 133 Mesa, Arizona
  phone: 480-354-7344
  phone_type:
  phone2:
  phone2_type:
  email: klausteam@klausteam.com
  url: https://klausteam.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://kennysgottheoffers.com/valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.klausteam.com/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your East Valley Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://kennysgottheoffers.com/valuation/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a East Valley Home?
    CTA_text2: Search the entire MLS for your East Valley home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://www.klausteam.com/
lender:
  show_section: true
  header_text: Featured Lender
  headshot_path: /img/b93ae50d0009767ad4e2b2f1-408x510.jpg
  logo_path: /img/lenderlogo.png
  logo_path_2:
  name: Steve Farrington
  license_number: 'NMLS #61852, Company NMLS #3029'
  phone: (480) 215-5590
  email: steve.farrington@myccmortgage.com
  url: https://crosscountrymortgage.com/Gaylord-Hansen-Team/Steven-Farrington/
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheKennyKlausTeam/
  linkedin_url: https://www.linkedin.com/company/the-kenny-klaus-team/
  gplus_url: https://plus.google.com/b/115578063320490631829/115578063320490631829
  youtube_url: >-
    https://www.youtube.com/user/TKKTAZ/about?edit_links=1#c4-primary-header-contents
  twitter_url: https://twitter.com/KennyKlausTeam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: East Valley Real Estate Podcast with Kenny Klaus
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    East Valley Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in East Valley,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Kenny Klaus
images:
  client_headshot_path: /uploads/klaus-team-headshot.png
  hero_logo_path: /uploads/ktreallogoforonlinepages.png
  logo_width_number: 50
  hero_text: East Valley Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2cc0f0'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
